version: "3.3"

services:
  proxy:
    build: .
    image: spuf/swarm-tcp-proxy
    environment:
      SERVICES: "app:8080"
      CONNECTION_TIMEOUT: 5m
    ports:
      - "8080:8080"
      - "3333:3333"
    depends_on:
      - app

  app:
    image: decentralize/proxy-responder
